### ISSUE TITLE
Code 31 with 23.12.2 HDR

### ISSUE THREAD

**Issue by francois-pasquier** [itsmikethetech/Virtual-Display-Driver#10] opened 2023-12-04 14:23 UTC
When following instructions with the latest release, it's not working.
The device is stuck in a Code 31 error state

**Comment by tomyan112** [comment] 2023-12-04 16:18
I have encountered the same error.
![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/9064351/ade43e81-2c70-41e0-a059-10cb1187ee74)

**Comment by ccbell42** [comment] 2023-12-04 17:55
Some people who reported that error on Youtube and Reddit were able to fix it by running Windows Update

**Comment by masgritz** [comment] 2023-12-04 20:23
I also have the same issue. It wasn't fixed by running Windows Update as suggested.

**Comment by itsmikethetech** [comment] 2023-12-07 12:39
I'm currently on the Canery Windows 11 Insider Build. For some reason, Microsoft doesn't seem to be uniformly distributing the driver base to all post 22H2 versions. Hoping it's fixed in an upcoming Windows update to push to all main releases.

**Comment by jccr** [comment] 2023-12-15 22:48
I'm also facing the same issue. I had 22H2 (September release) and was facing Code 31.

I used Windows update to do a feature update to 23H2, uninstalled the driver and reinstalled and also facing Code 31 😿 

Is there anything that could be done to help debug or diagnose this?

**Comment by Kureka** [comment] 2023-12-22 12:18
I got same problem here, please help

**Comment by masgritz** [comment] 2023-12-22 13:56
Heads up, mine suddenly started working after update Windows 11 23H2 KB5033375 got installed

**Comment by sieskei** [comment] 2023-12-22 16:54
> Heads up, mine suddenly started working after update Windows 11 23H2 KB5033375 got installed

I can confirm, after today update it's working.
[UPDATE](https://support.microsoft.com/en-us/topic/december-12-2023-kb5033375-os-builds-22621-2861-and-22631-2861-90f983aa-efb6-4caa-9cab-7e5cfa00ed36)

**Comment by Rafalskyy** [comment] 2023-12-29 13:59
I still have 31 code with 23H2 (22631.2861). Any solutions? Version without hdr works fine.

**Comment by jccr** [comment] 2024-01-01 09:36
> Heads up, mine suddenly started working after update Windows 11 23H2 KB5033375 got installed

It started working for me too! Checked my update history and had KB5033375 installed recently.

**Comment by itsmikethetech** [comment] 2024-01-02 17:27
> Mine still has this issue, on 23H2, fully updated, rebooted etc. ![image](https://private-user-images.githubusercontent.com/49495505/293743804-e84e8843-5b64-4bcc-9f34-edf221bad86a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyMTY3MTYsIm5iZiI6MTcwNDIxNjQxNiwicGF0aCI6Ii80OTQ5NTUwNS8yOTM3NDM4MDQtZTg0ZTg4NDMtNWI2NC00YmNjLTlmMzQtZWRmMjIxYmFkODZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAyVDE3MjY1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkxMTVjODEzN2Q4MzY4ZmQ4MmFjNDQwOGQzYTM5ZDRiMTJkNDdiOTA2OWNiNDg2Y2MzZDk3YjJjMTFiYzdkMWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3SIYaeNCTCxZYZL2F2TyyIU5YxXIl4ZEHFy9H4ZP5Cw)

Is the options.txt file in the C:\IddSampleDriver\ folder when installing?

**Comment by xsxavier** [comment] 2024-01-02 17:49
Yes I have tried it twice, uninstalled the driver. First time just the option.txt in the folder, second time I just put the entire folder from the zip in C:\. No difference.
I am currently trying a beta build for Windows, see if that makes any difference.
![image](https://github.com/itsmikethetech/Virtual-Display-Driver/assets/49495505/eee0f1ff-6577-43d6-ae7c-32630c697bd0)

**Comment by JM33** [comment] 2024-01-03 02:46
I was getting this error and noticed [itsmikethetech](https://github.com/itsmikethetech) asked if the options.txt file is in the  C:\IddSampleDriver\ folder when installing?  Well the file in the archive is titled option.txt, not options.txt.  So i renamed it to options.txt and the driver installed fine.  Hope this helps others!

**Comment by JM33** [comment] 2024-01-03 03:17
I thought i had fixed this by changing the option.txt to options.txt, but that didn't work.  The HDR version gives me this error, the standard works.  Same problem as xsxavier above.  Will use standard until a fix is available

**Comment by helloavo** [comment] 2024-01-05 15:48
I had the same issue until I connect my laptop to my eGPU (Nvidia 2080ti) that had a HDR display attached. 
Suddenly started working, even after rebooting and without the eGPU attached.

**Comment by Cynary** [comment] 2024-01-11 03:20
Same issue - even tried going into the beta channel and installing that update. Multiple uninstall/installs later, and it still doesn't work.
Non-HDR works properly - I'm hoping this is some staged release by Microsoft, so we'll eventually get it (though it's weird it's not available in the beta channel).

**Comment by MitoZ** [comment] 2024-01-15 23:38
I had the same issue but with both drivers (HDR and non-HDR). Windows 11 22H2 is updated to the latest version T_T

**Comment by Skyro620** [comment] 2024-01-21 20:50
FYI for folks who are still having this issue a clean reinstall of windows 11 fixed it for me.

**Comment by Toucherj** [comment] 2024-01-31 23:06
WHAT?!?!?
I found out the issue on mine.
The folder needs to be in the c:\ drive to be able to install properly.
C:\IddSampleDriver

**Comment by MitoZ** [comment] 2024-02-01 22:46
> WHAT?!?!? I found out the issue on mine. The folder needs to be in the c:\ drive to be able to install properly. C:\IddSampleDriver

I approve, it helped me too. Fresh and updated win 11 + C:\IddSampleDriver

**Comment by masgritz** [comment] 2024-02-01 23:04
@Toucherj @MitoZ what you guys mentioned is part of the basic install instructions. The problem we were having was because of Microsoft not rolling out part of the driver base through the updates, but that seems mostly sorted out by now.

**Comment by bgradid** [comment] 2024-03-09 18:35
I was running for a while and after a recent os update I started getting the code 31 error again. Even switching to the beta channel hasn't fixed it. I've had to revert to the non-hdr version again.

**Comment by julianrios** [comment] 2024-03-12 04:32
> WHAT?!?!? I found out the issue on mine. The folder needs to be in the c:\ drive to be able to install properly. C:\IddSampleDriver

Thanks dude this fixed my issue 23H2

**Comment by evertonmdz** [comment] 2024-03-26 20:03
Only the version without HDR works here, with HDR in version 23H2, build 22635.3350 also has error code 31!

**Comment by chrisssj2** [comment] 2024-06-06 02:46
Had the error on 24h2. putting on root C drive fixed like said here!

**Comment by anderse77** [comment] 2024-06-12 21:27
Teinstall windows 11 i quiet drastic. Any other way? I get encoding error from mopnlight on ios.

**Comment by stonksCode** [comment] 2024-06-18 16:35
Guys, going through this thread, I found what MY issue was, not sure if it will be the case for everyone else

On the main instructions, it says

Copy option.txt to **C:\IddSampleDriver\option.txt** before installing the driver (important!).

This is incorrect. It is supposed to be IddSampleDrive, not DRIVER. After changing the folder name, it installed no issue. This is also a fresh Win 11 install, fully updated prior to install.

**Closed** 2024-11-23 16:01 UTC
Labels: bug
